version: '3'

services:
  mongodb:
    #image: mongo:3.6.23
    image: mongo:latest
    container_name: "mongodb"
    networks:
      - my_shared_network
      #- sdiff-inet
    ports:
      - "27017:27017"
    volumes:
      - ${HOME_PATH_LINUX}:/data/db
  fuseki:
    image: secoresearch/fuseki
    container_name: fuseki
    networks:
      - my_shared_network
      #- sdiff-inet
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: fuseki
      QUERY_TIMEOUT: 600000
    volumes:
      - /home/terminology/fuseki/fuseki-data:/fuseki-base/databases
      - /home/terminology/fuseki/fuseki-configuration:/fuseki-base/configuration
  history-back:
    image: history-back:1.0
    container_name: history-back
    networks:
      - my_shared_network
      #- sdiff-inet
    build:
      context: .
    ports:
      - "9090:9090"
networks:
  #sdiff-inet:
  my_shared_network:
    driver: bridge
